/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clears the cookie for one surface.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/room-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Room Login
         * @description Room name (dropdown) + event password. Sets display_sid or control_sid.
         */
        post: operations["room_login_api_auth_room_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login Options
         * @description Rooms for the login dropdown. No auth. Bounded (MAX_LOGIN_ROOMS).
         */
        get: operations["login_options_api_auth_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/staff-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Staff Login
         * @description Named staff account. Sets staff_sid.
         */
        post: operations["staff_login_api_auth_staff_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Command
         * @description One command, idempotent on command_id. Needs X-Proctor-Client.
         */
        post: operations["post_command_api_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who is logged in on this surface (cookies are HttpOnly, so the UI asks).
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room Snapshot
         * @description Polling fallback. Served from memory. 304 when version <= since_version.
         */
        get: operations["room_snapshot_api_rooms__room_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room Stream
         * @description SSE: current snapshot immediately, then every change, plus heartbeats.
         */
        get: operations["room_stream_api_rooms__room_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Staff Rooms
         * @description All rooms' snapshots (staff dashboard first load).
         */
        get: operations["staff_rooms_api_staff_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Staff Stream
         * @description SSE: a snapshot per room on connect, then every change in any room, plus heartbeats.
         */
        get: operations["staff_stream_api_staff_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Time
         * @description Clock-sync probe. No auth. Never touches Postgres.
         */
        get: operations["get_time_api_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustCommand */
        AdjustCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Delta Ms */
            delta_ms: number;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "adjust";
        };
        /**
         * CommandOutcome
         * @enum {string}
         */
        CommandOutcome: "applied" | "rejected";
        /** CommandResponse */
        CommandResponse: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            outcome: components["schemas"]["CommandOutcome"];
            reason: components["schemas"]["RejectionReason"] | null;
            /** Replayed */
            replayed: boolean;
            snapshot: components["schemas"]["RoomSnapshot"];
        };
        /** EndCommand */
        EndCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "end";
        };
        /**
         * ErrorCode
         * @description HTTP-level errors. These are NOT recorded as events (see docs/protocol.md §6.5).
         * @enum {string}
         */
        ErrorCode: "invalid_request" | "invalid_credentials" | "unauthenticated" | "forbidden" | "unknown_room" | "unknown_session" | "command_id_conflict" | "rate_limited" | "unavailable" | "internal";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /** Heartbeat */
        Heartbeat: {
            /** Server Time Ms */
            server_time_ms: number;
        };
        /**
         * HeartbeatMessage
         * @description SSE frame: `event: heartbeat`, `data: <Heartbeat as JSON>`.
         */
        HeartbeatMessage: {
            data: components["schemas"]["Heartbeat"];
            /**
             * Event
             * @constant
             */
            event: "heartbeat";
        };
        /** LoginOptionsResponse */
        LoginOptionsResponse: {
            /** Event Id */
            event_id: string;
            /** Event Name */
            event_name: string;
            /** Rooms */
            rooms: components["schemas"]["LoginRoomOption"][];
        };
        /** LoginRoomOption */
        LoginRoomOption: {
            /** Name */
            name: string;
            /** Room Id */
            room_id: string;
        };
        /** PauseCommand */
        PauseCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pause";
        };
        /** PermitCommand */
        PermitCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "permit";
        };
        /**
         * RejectionReason
         * @description Why an event was recorded but not applied. Only the fold produces these.
         * @enum {string}
         */
        RejectionReason: "claimed_at_out_of_bounds" | "session_ended" | "already_permitted" | "not_permitted" | "already_started" | "not_running" | "not_paused" | "not_started" | "adjust_out_of_range" | "stale_session";
        /** ResumeCommand */
        ResumeCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resume";
        };
        /** RoomIdentity */
        RoomIdentity: {
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "room";
            /** Room Id */
            room_id: string;
            /** Room Name */
            room_name: string;
            /**
             * Surface
             * @enum {string}
             */
            surface: "display" | "control";
        };
        /** RoomLoginRequest */
        RoomLoginRequest: {
            /** Password */
            password: string;
            /** Room Id */
            room_id: string;
            /**
             * Surface
             * @enum {string}
             */
            surface: "display" | "control";
        };
        /**
         * RoomSnapshot
         * @description Everything a room device needs to show and tick the timer. Sent in full every time.
         */
        RoomSnapshot: {
            /** Room Id */
            room_id: string;
            /** Room Name */
            room_name: string;
            /** Server Time Ms */
            server_time_ms: number;
            /** Session Id */
            session_id: string;
            /** Test Name */
            test_name: string;
            timer: components["schemas"]["TimerSnapshot"];
            /** Version */
            version: number;
        };
        /**
         * SnapshotMessage
         * @description SSE frame: `event: snapshot`, `id: <version>`, `data: <RoomSnapshot as JSON>`.
         */
        SnapshotMessage: {
            data: components["schemas"]["RoomSnapshot"];
            /**
             * Event
             * @constant
             */
            event: "snapshot";
        };
        /** StaffIdentity */
        StaffIdentity: {
            /** Account Id */
            account_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "staff";
            role: components["schemas"]["StaffRole"];
            /** Username */
            username: string;
        };
        /** StaffLoginRequest */
        StaffLoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * StaffRole
         * @enum {string}
         */
        StaffRole: "admin" | "pm" | "to";
        /** StaffRoomsResponse */
        StaffRoomsResponse: {
            /** Rooms */
            rooms: components["schemas"]["RoomSnapshot"][];
        };
        /** StartCommand */
        StartCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "start";
        };
        /**
         * Surface
         * @enum {string}
         */
        Surface: "display" | "control" | "staff";
        /** TimeResponse */
        TimeResponse: {
            /** Server Time Ms */
            server_time_ms: number;
        };
        /**
         * TimerSnapshot
         * @description The folded timer state (plan §3.3).
         *
         *     remaining(now) = max(0, duration_ms + adjust_total_ms - elapsed_banked_ms
         *                             - (now - running_since_ms if RUNNING else 0))
         */
        TimerSnapshot: {
            /** Adjust Total Ms */
            adjust_total_ms: number;
            /** Duration Ms */
            duration_ms: number;
            /** Elapsed Banked Ms */
            elapsed_banked_ms: number;
            /** Running Since Ms */
            running_since_ms: number | null;
            status: components["schemas"]["TimerStatus"];
        };
        /**
         * TimerStatus
         * @enum {string}
         */
        TimerStatus: "NOT_PERMITTED" | "PERMITTED" | "RUNNING" | "PAUSED" | "ENDED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_api_auth_logout_post: {
        parameters: {
            query: {
                surface: components["schemas"]["Surface"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    room_login_api_auth_room_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomIdentity"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_options_api_auth_rooms_get: {
        parameters: {
            query?: {
                practice?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOptionsResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    staff_login_api_auth_staff_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffIdentity"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_command_api_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermitCommand"] | components["schemas"]["StartCommand"] | components["schemas"]["PauseCommand"] | components["schemas"]["ResumeCommand"] | components["schemas"]["EndCommand"] | components["schemas"]["AdjustCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query: {
                surface: components["schemas"]["Surface"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomIdentity"] | components["schemas"]["StaffIdentity"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    room_snapshot_api_rooms__room_id__snapshot_get: {
        parameters: {
            query?: {
                since_version?: number | null;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description Nothing newer than since_version */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    room_stream_api_rooms__room_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream. Frames are SnapshotMessage and HeartbeatMessage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["SnapshotMessage"] | components["schemas"]["HeartbeatMessage"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    staff_rooms_api_staff_rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRoomsResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    staff_stream_api_staff_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream. Frames are SnapshotMessage and HeartbeatMessage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["SnapshotMessage"] | components["schemas"]["HeartbeatMessage"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_time_api_time_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeResponse"];
                };
            };
        };
    };
}
