/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clears the cookie for one surface.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/room-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Room Login
         * @description Room name (dropdown) + event password. Sets display_sid or control_sid.
         */
        post: operations["room_login_api_auth_room_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login Options
         * @description Rooms for the login dropdown. No auth. Bounded (MAX_LOGIN_ROOMS).
         */
        get: operations["login_options_api_auth_rooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/staff-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Staff Login
         * @description Named staff account. Sets staff_sid.
         */
        post: operations["staff_login_api_auth_staff_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Command
         * @description One command, idempotent on command_id. Needs X-Proctor-Client.
         */
        post: operations["post_command_api_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Who is logged in on this surface (cookies are HttpOnly, so the UI asks).
         */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room Snapshot
         * @description Polling fallback. Served from memory. 304 when version <= since_version.
         */
        get: operations["room_snapshot_api_rooms__room_id__snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Room Stream
         * @description SSE: current snapshot immediately, then every change, plus heartbeats.
         *     `cid` is a random id the page picks so it can end this stream early (0.5.0).
         */
        get: operations["room_stream_api_rooms__room_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/{room_id}/stream/{cid}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Room Stream
         * @description A page is closing: end its stream now so presence updates at once. Needs X-Proctor-Client. 0.5.0.
         */
        post: operations["close_room_stream_api_rooms__room_id__stream__cid__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/clarifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clarifications
         * @description Admin: every clarification, newest first, hidden included. Added in 0.6.0.
         */
        get: operations["list_clarifications_api_staff_clarifications_get"];
        put?: never;
        /**
         * Post Clarification
         * @description Admin posts text to all rooms (room_ids null) or a subset. Added in 0.6.0.
         */
        post: operations["post_clarification_api_staff_clarifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/clarifications/{clarification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Clarification
         * @description Admin deletes a clarification, or (`room_id`) from one room only. Soft since 0.8.0:
         *     restorable until emptied. Added in 0.7.0.
         */
        delete: operations["delete_clarification_api_staff_clarifications__clarification_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Clarification
         * @description Admin edits (`body`; old wording stays, struck out) or hides/unhides (`hidden`, one
         *     room with `room_id`). Added in 0.6.0 as hide only; edit and per-room in 0.7.0. With
         *     `body` and `room_id` (0.8.0) that room moves to a new edited copy, which is returned.
         */
        patch: operations["update_clarification_api_staff_clarifications__clarification_id__patch"];
        trace?: never;
    };
    "/api/staff/clarifications/{clarification_id}/empty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Empty Clarification
         * @description Admin wipes a deleted clarification from the database for good. Added in 0.8.0.
         */
        post: operations["empty_clarification_api_staff_clarifications__clarification_id__empty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/clarifications/{clarification_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Clarification
         * @description Admin undoes a delete, everywhere or (`room_id`) in one room. Added in 0.8.0.
         */
        post: operations["restore_clarification_api_staff_clarifications__clarification_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Staff Rooms
         * @description All rooms' snapshots (staff dashboard first load).
         */
        get: operations["staff_rooms_api_staff_rooms_get"];
        put?: never;
        /**
         * Create Room
         * @description Admin adds a room (name, duration_min default 180). Added in 0.2.0.
         */
        post: operations["create_room_api_staff_rooms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/rooms/{room_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Room
         * @description Admin: soft delete (hide). Not while RUNNING or PAUSED. Signs the room out. 0.4.0.
         */
        delete: operations["delete_room_api_staff_rooms__room_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Room
         * @description Admin edits duration (before start only) and/or test label. Added in 0.3.0.
         */
        patch: operations["update_room_api_staff_rooms__room_id__patch"];
        trace?: never;
    };
    "/api/staff/rooms/{room_id}/empty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Empty Room
         * @description Admin wipes a deleted room and its history from the database for good. 0.8.0.
         */
        post: operations["empty_room_api_staff_rooms__room_id__empty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/rooms/{room_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Room
         * @description Admin: fresh not-started timer for a PAUSED or ENDED room. Added in 0.4.0.
         */
        post: operations["reset_room_api_staff_rooms__room_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/rooms/{room_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Room
         * @description Admin: undo a soft delete. Added in 0.4.0.
         */
        post: operations["restore_room_api_staff_rooms__room_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Staff Stream
         * @description SSE: a snapshot per room on connect, then every change in any room, plus heartbeats.
         *     With `?clarifications=1` (0.8.0) also a `clarifications` event (the admin list, same body
         *     as GET /api/staff/clarifications) on connect and after every clarification change.
         *     A `room_removed` event (`{room_id}`, 0.8.0) follows an Empty of a deleted room.
         */
        get: operations["staff_stream_api_staff_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Time
         * @description Clock-sync probe. No auth. Never touches Postgres.
         */
        get: operations["get_time_api_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustCommand */
        AdjustCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /** Delta Ms */
            delta_ms: number;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "adjust";
        };
        /** ClarificationAdmin */
        ClarificationAdmin: {
            /** Body */
            body: string;
            /** Created At Ms */
            created_at_ms: number;
            /** Deleted */
            deleted: boolean;
            /** Edited At Ms */
            edited_at_ms: number | null;
            /** Edited Room Ids */
            edited_room_ids: string[];
            /** Hidden */
            hidden: boolean;
            /** Hidden Room Ids */
            hidden_room_ids: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Previous */
            previous: string[];
            /** Removed Room Ids */
            removed_room_ids: string[];
            /** Room Ids */
            room_ids: string[] | null;
        };
        /**
         * ClarificationOut
         * @description One visible clarification, as a room device sees it.
         */
        ClarificationOut: {
            /** Body */
            body: string;
            /** Created At Ms */
            created_at_ms: number;
            /** Edited At Ms */
            edited_at_ms: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Previous */
            previous: string[];
        };
        /** ClarificationsResponse */
        ClarificationsResponse: {
            /** Clarifications */
            clarifications: components["schemas"]["ClarificationAdmin"][];
        };
        /**
         * CommandOutcome
         * @enum {string}
         */
        CommandOutcome: "applied" | "rejected";
        /** CommandResponse */
        CommandResponse: {
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            outcome: components["schemas"]["CommandOutcome"];
            reason: components["schemas"]["RejectionReason"] | null;
            /** Replayed */
            replayed: boolean;
            snapshot: components["schemas"]["RoomSnapshot"];
        };
        /**
         * CreateClarificationRequest
         * @description Admin posts a clarification (wireframe: Admin · Clarifications). null room_ids = all.
         */
        CreateClarificationRequest: {
            /** Body */
            body: string;
            /** Room Ids */
            room_ids?: string[] | null;
        };
        /**
         * CreateRoomRequest
         * @description Admin adds a room (wireframe: Admin · Timers). Duration defaults to 180 minutes.
         */
        CreateRoomRequest: {
            /** Doc Url */
            doc_url?: string | null;
            /**
             * Duration Min
             * @default 180
             */
            duration_min: number;
            /** Name */
            name: string;
            /** Test Name */
            test_name?: string | null;
        };
        /** EndCommand */
        EndCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "end";
        };
        /**
         * ErrorCode
         * @description HTTP-level errors. These are NOT recorded as events (see docs/protocol.md §6.5).
         * @enum {string}
         */
        ErrorCode: "invalid_request" | "invalid_credentials" | "unauthenticated" | "forbidden" | "unknown_room" | "unknown_session" | "command_id_conflict" | "rate_limited" | "unavailable" | "internal";
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorCode"];
            /** Message */
            message: string;
        };
        /** Heartbeat */
        Heartbeat: {
            /** Server Time Ms */
            server_time_ms: number;
        };
        /**
         * HeartbeatMessage
         * @description SSE frame: `event: heartbeat`, `data: <Heartbeat as JSON>`.
         */
        HeartbeatMessage: {
            data: components["schemas"]["Heartbeat"];
            /**
             * Event
             * @constant
             */
            event: "heartbeat";
        };
        /** LoginOptionsResponse */
        LoginOptionsResponse: {
            /** Event Id */
            event_id: string;
            /** Event Name */
            event_name: string;
            /** Rooms */
            rooms: components["schemas"]["LoginRoomOption"][];
        };
        /** LoginRoomOption */
        LoginRoomOption: {
            /** Name */
            name: string;
            /** Room Id */
            room_id: string;
        };
        /** PauseCommand */
        PauseCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pause";
        };
        /** PermitCommand */
        PermitCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "permit";
        };
        /**
         * RejectionReason
         * @description Why an event was recorded but not applied. Only the fold produces these.
         * @enum {string}
         */
        RejectionReason: "claimed_at_out_of_bounds" | "session_ended" | "already_permitted" | "not_permitted" | "already_started" | "not_running" | "not_paused" | "not_started" | "adjust_out_of_range" | "stale_session";
        /**
         * ResetRoomRequest
         * @description Admin resets a paused or finished room to a fresh, not-started timer. `session_id` is the
         *     session the admin was looking at, so two admins can't reset twice by accident.
         */
        ResetRoomRequest: {
            /** Session Id */
            session_id: string;
        };
        /** ResumeCommand */
        ResumeCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "resume";
        };
        /** RoomIdentity */
        RoomIdentity: {
            /** Event Id */
            event_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "room";
            /** Room Id */
            room_id: string;
            /** Room Name */
            room_name: string;
            /**
             * Surface
             * @enum {string}
             */
            surface: "display" | "control";
        };
        /** RoomLoginRequest */
        RoomLoginRequest: {
            /** Password */
            password: string;
            /** Room Id */
            room_id: string;
            /**
             * Surface
             * @enum {string}
             */
            surface: "display" | "control";
        };
        /**
         * RoomPresence
         * @description Who has this room's pages open (staff stream only). `control` = proctor page.
         */
        RoomPresence: {
            control: components["schemas"]["SurfacePresence"];
            display: components["schemas"]["SurfacePresence"];
            /** Room Id */
            room_id: string;
        };
        /**
         * RoomSnapshot
         * @description Everything a room device needs to show and tick the timer. Sent in full every time.
         */
        RoomSnapshot: {
            /** Clarifications */
            clarifications: components["schemas"]["ClarificationOut"][];
            /** Deleted */
            deleted: boolean;
            /** Doc Url */
            doc_url: string | null;
            /** Room Id */
            room_id: string;
            /** Room Name */
            room_name: string;
            /** Server Time Ms */
            server_time_ms: number;
            /** Session Id */
            session_id: string;
            /** Test Name */
            test_name: string;
            timer: components["schemas"]["TimerSnapshot"];
            /** Version */
            version: number;
        };
        /**
         * SnapshotMessage
         * @description SSE frame: `event: snapshot`, `id: <version>`, `data: <RoomSnapshot as JSON>`.
         */
        SnapshotMessage: {
            data: components["schemas"]["RoomSnapshot"];
            /**
             * Event
             * @constant
             */
            event: "snapshot";
        };
        /** StaffIdentity */
        StaffIdentity: {
            /** Account Id */
            account_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "staff";
            role: components["schemas"]["StaffRole"];
            /** Username */
            username: string;
        };
        /** StaffLoginRequest */
        StaffLoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * StaffRole
         * @enum {string}
         */
        StaffRole: "admin" | "pm" | "to";
        /** StaffRoomsResponse */
        StaffRoomsResponse: {
            /** Presence */
            presence?: components["schemas"]["RoomPresence"][];
            /** Rooms */
            rooms: components["schemas"]["RoomSnapshot"][];
        };
        /** StartCommand */
        StartCommand: {
            /** Claimed At Ms */
            claimed_at_ms: number;
            /**
             * Command Id
             * Format: uuid
             */
            command_id: string;
            /**
             * Device Id
             * Format: uuid
             */
            device_id: string;
            /** Proctor Name */
            proctor_name?: string | null;
            /** Reason */
            reason?: string | null;
            /** Room Id */
            room_id: string;
            /** Session Id */
            session_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "start";
        };
        /**
         * Surface
         * @enum {string}
         */
        Surface: "display" | "control" | "staff";
        /** SurfacePresence */
        SurfacePresence: {
            /** Last Seen Ms */
            last_seen_ms?: number | null;
            /** Online */
            online: number;
        };
        /** TimeResponse */
        TimeResponse: {
            /** Server Time Ms */
            server_time_ms: number;
        };
        /**
         * TimerSnapshot
         * @description The folded timer state (plan §3.3).
         *
         *     remaining(now) = max(0, duration_ms + adjust_total_ms - elapsed_banked_ms
         *                             - (now - running_since_ms if RUNNING else 0))
         */
        TimerSnapshot: {
            /** Adjust Total Ms */
            adjust_total_ms: number;
            /** Duration Ms */
            duration_ms: number;
            /** Elapsed Banked Ms */
            elapsed_banked_ms: number;
            /** Running Since Ms */
            running_since_ms: number | null;
            status: components["schemas"]["TimerStatus"];
        };
        /**
         * TimerStatus
         * @enum {string}
         */
        TimerStatus: "NOT_PERMITTED" | "PERMITTED" | "RUNNING" | "PAUSED" | "ENDED";
        /**
         * UpdateClarificationRequest
         * @description Exactly one of `hidden` (hide/unhide) or `body` (edit; the old wording stays visible,
         *     struck out). `room_id` limits the action to one room. A per-room edit moves that room to
         *     a new copy with the edited text and returns the copy (0.8.0).
         */
        UpdateClarificationRequest: {
            /** Body */
            body?: string | null;
            /** Hidden */
            hidden?: boolean | null;
            /** Room Id */
            room_id?: string | null;
        };
        /**
         * UpdateRoomRequest
         * @description Admin edits a room that has not started (wireframe: Edit…). Omitted fields are unchanged.
         *
         *     Duration can only change before the timer starts; use `adjust` (+/- time) once running.
         */
        UpdateRoomRequest: {
            /** Doc Url */
            doc_url?: string | null;
            /** Duration Min */
            duration_min?: number | null;
            /** Name */
            name?: string | null;
            /** Test Name */
            test_name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout_api_auth_logout_post: {
        parameters: {
            query: {
                surface: components["schemas"]["Surface"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    room_login_api_auth_room_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomIdentity"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login_options_api_auth_rooms_get: {
        parameters: {
            query?: {
                practice?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOptionsResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    staff_login_api_auth_staff_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffIdentity"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_command_api_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PermitCommand"] | components["schemas"]["StartCommand"] | components["schemas"]["PauseCommand"] | components["schemas"]["ResumeCommand"] | components["schemas"]["EndCommand"] | components["schemas"]["AdjustCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query: {
                surface: components["schemas"]["Surface"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomIdentity"] | components["schemas"]["StaffIdentity"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    room_snapshot_api_rooms__room_id__snapshot_get: {
        parameters: {
            query?: {
                since_version?: number | null;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description Nothing newer than since_version */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    room_stream_api_rooms__room_id__stream_get: {
        parameters: {
            query?: {
                surface?: ("control" | "display") | null;
                cid?: string | null;
            };
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream. Frames are SnapshotMessage, HeartbeatMessage and (staff stream only) PresenceMessage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["SnapshotMessage"] | components["schemas"]["HeartbeatMessage"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    close_room_stream_api_rooms__room_id__stream__cid__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
                cid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_clarifications_api_staff_clarifications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationsResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_clarification_api_staff_clarifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClarificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationAdmin"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_clarification_api_staff_clarifications__clarification_id__delete: {
        parameters: {
            query?: {
                room_id?: string | null;
            };
            header?: never;
            path: {
                clarification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_clarification */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room, not_in_room */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_clarification_api_staff_clarifications__clarification_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clarification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClarificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationAdmin"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_clarification */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description empty, unknown_room, not_in_room, edit_limit, deleted */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    empty_clarification_api_staff_clarifications__clarification_id__empty_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clarification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_clarification */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description not_deleted */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_clarification_api_staff_clarifications__clarification_id__restore_post: {
        parameters: {
            query?: {
                room_id?: string | null;
            };
            header?: never;
            path: {
                clarification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarificationAdmin"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_clarification */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room, not_in_room */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    staff_rooms_api_staff_rooms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRoomsResponse"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_room_api_staff_rooms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description room_exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_room_api_staff_rooms__room_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description room_in_progress */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_room_api_staff_rooms__room_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description room_started */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    empty_room_api_staff_rooms__room_id__empty_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description not_deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reset_room_api_staff_rooms__room_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetRoomRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description not_resettable | stale_session | room_deleted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_room_api_staff_rooms__room_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                room_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSnapshot"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    staff_stream_api_staff_stream_get: {
        parameters: {
            query?: {
                clarifications?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream. Frames are SnapshotMessage, HeartbeatMessage and (staff stream only) PresenceMessage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": components["schemas"]["SnapshotMessage"] | components["schemas"]["HeartbeatMessage"];
                };
            };
            /** @description unauthenticated / invalid_credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description unknown_room / unknown_session */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description invalid_request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description rate_limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_time_api_time_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeResponse"];
                };
            };
        };
    };
}
